-   name: web
    hosts: web
    roles:
        - roles/apache
        - roles/haproxy
    user: robot
    sudo: true
    environment:
        http_proxy: http://user:pass@proxy.host:8080
        https_proxy: http://user:pass@proxy.host:8080

-   name: graphite
    hosts: graphite
    roles:
        - roles/graphite 
    user: robot
    sudo: true
    environment:
        http_proxy: http://user:pass@proxy.host:8080
        https_proxy: http://user:pass@proxy.host:8080
